apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "https-portal.fullname" . }}
  labels:
    {{- include "https-portal.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "https-portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "https-portal.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "https-portal.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: ssl
              containerPort: 443
              protocol: TCP
          envFrom:
          - configMapRef:
              name: https-portal-env
          - configMapRef:
              name: outline-env
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
           {{- if .Values.global.persistence.enabled }}
          volumeMounts:
          - name: https-portal-data
            mountPath: /var/lib/postgresql/data
          {{- end }}
      {{- if .Values.global.persistence.enabled }}
      volumes:
      - name: https-portal-data
        persistentVolumeClaim:
          claimName: https-portal-data
      {{- end }}
     {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
