apiVersion: v1
data:
  default.conf: |-
    upstream wger {
        server wger-web:8000;
    }

    server {

        listen 80;

        location / {
            proxy_pass http://wger;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
            proxy_redirect off;
        }

        location /static/ {
            alias /wger/static/;
        }

        location /media/ {
            alias /wger/media/;
        }

        # Increase max body size to allow for video uploads
        client_max_body_size 100M;
    }
kind: ConfigMap
metadata:
  name: wger-nginx-config
  labels: {{- include "nginx.labels" . | nindent 4 }}
