{{- if and .Values.persistence.enabled (not .Values.persistence.nfs_enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  labels: {{- include "radarr.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}
