{{- if .Values.global.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: {{- include "wger.labels" . | nindent 4 }}
  name: media
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: {{ .Values.global.persistence.storageClass }}
{{- end }}
