{{- if .Values.global.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: {{- include "wger.labels" . | nindent 4 }}
  name: postgres-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: {{ .Values.global.persistence.storageClass }}
{{- end }}
